// ═══════════════════════════════════════════════════════════════════════════
// REPORTER.JS - Analysis Report Generator
// Excel Intelligence Bot - 2025 Edition
// ═══════════════════════════════════════════════════════════════════════════

import ExcelJS from 'exceljs';
import { BOT_CONFIG, ISSUE_TYPES, QUALITY_THRESHOLDS } from '../utils/constants.js';
import { 
  formatRupiah, 
  formatNumber, 
  formatPercentage,
  formatDate,
  formatDateTime 
} from '../utils/helpers.js';

// ─────────────────────────────────────────────────────────────────────────────
// MAIN REPORTER CLASS
// ─────────────────────────────────────────────────────────────────────────────

export class ReportGenerator {
  constructor(options = {}) {
    this.options = {
      companyName: options.companyName || '',
      includeCharts: options.includeCharts ?? false,
      includeRawData: options.includeRawData ?? true,
      language: options.language || 'id', // 'id' or 'en'
      ...options
    };
    
    this.labels = this.getLabels(this.options.language);
  }

  /**
   * Get localized labels
   */
  getLabels(lang) {
    const labels = {
      id: {
        analysisReport: 'LAPORAN ANALISIS DATA',
        summary: 'Ringkasan',
        qualityScore: 'Skor Kualitas',
        issues: 'Masalah Ditemukan',
        suggestions: 'Saran Perbaikan',
        statistics: 'Statistik',
        columnAnalysis: 'Analisis Kolom',
        rawData: 'Data Mentah',
        totalRows: 'Total Baris',
        totalColumns: 'Total Kolom',
        analysisTime: 'Waktu Analisis',
        generatedAt: 'Dibuat pada',
        generator: 'Dibuat oleh',
        grade: 'Grade',
        completeness: 'Kelengkapan',
        consistency: 'Konsistensi',
        validity: 'Validitas',
        uniqueness: 'Keunikan',
        column: 'Kolom',
        type: 'Tipe',
        fillRate: 'Terisi',
        uniqueValues: 'Nilai Unik',
        samples: 'Contoh',
        severity: 'Tingkat',
        row: 'Baris',
        message: 'Pesan',
        fix: 'Perbaikan',
        priority: 'Prioritas',
        action: 'Aksi',
        impact: 'Dampak',
        count: 'Jumlah',
        sum: 'Total',
        average: 'Rata-rata',
        min: 'Minimum',
        max: 'Maximum',
        high: 'Tinggi',
        medium: 'Sedang',
        low: 'Rendah',
        error: 'Error',
        warning: 'Peringatan',
        info: 'Info'
      },
      en: {
        analysisReport: 'DATA ANALYSIS REPORT',
        summary: 'Summary',
        qualityScore: 'Quality Score',
        issues: 'Issues Found',
        suggestions: 'Suggestions',
        statistics: 'Statistics',
        columnAnalysis: 'Column Analysis',
        rawData: 'Raw Data',
        totalRows: 'Total Rows',
        totalColumns: 'Total Columns',
        analysisTime: 'Analysis Time',
        generatedAt: 'Generated at',
        generator: 'Generated by',
        grade: 'Grade',
        completeness: 'Completeness',
        consistency: 'Consistency',
        validity: 'Validity',
        uniqueness: 'Uniqueness',
        column: 'Column',
        type: 'Type',
        fillRate: 'Fill Rate',
        uniqueValues: 'Unique Values',
        samples: 'Samples',
        severity: 'Severity',
        row: 'Row',
        message: 'Message',
        fix: 'Fix',
        priority: 'Priority',
        action: 'Action',
        impact: 'Impact',
        count: 'Count',
        sum: 'Sum',
        average: 'Average',
        min: 'Minimum',
        max: 'Maximum',
        high: 'High',
        medium: 'Medium',
        low: 'Low',
        error: 'Error',
        warning: 'Warning',
        info: 'Info'
      }
    };
    
    return labels[lang] || labels.id;
  }

  /**
   * 📊 GENERATE FULL ANALYSIS REPORT
   */
  async generateAnalysisReport(analysisResult, parsedData = null, sheetName = null) {
    const workbook = new ExcelJS.Workbook();
    
    workbook.creator = 'Excel Intelligence Bot';
    workbook.created = new Date();
    
    // 1️⃣ Summary Sheet
    await this.addSummarySheet(workbook, analysisResult);
    
    // 2️⃣ Quality Score Sheet
    await this.addQualityScoreSheet(workbook, analysisResult.qualityScore);
    
    // 3️⃣ Column Analysis Sheet
    await this.addColumnAnalysisSheet(workbook, analysisResult.columnAnalysis);
    
    // 4️⃣ Issues Sheet
    if (analysisResult.issues.total > 0) {
      await this.addIssuesSheet(workbook, analysisResult.issues);
    }
    
    // 5️⃣ Suggestions Sheet
    if (analysisResult.suggestions.length > 0) {
      await this.addSuggestionsSheet(workbook, analysisResult.suggestions);
    }
    
    // 6️⃣ Statistics Sheet
    if (Object.keys(analysisResult.statistics).length > 0) {
      await this.addStatisticsSheet(workbook, analysisResult.statistics);
    }
    
    // 7️⃣ Raw Data Sheet (optional)
    if (this.options.includeRawData && parsedData) {
      await this.addRawDataSheet(workbook, parsedData, sheetName);
    }
    
    // Generate buffer
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // SUMMARY SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addSummarySheet(workbook, analysisResult) {
    const ws = workbook.addWorksheet(this.labels.summary, {
      properties: { tabColor: { argb: 'FF2F5496' } }
    });
    
    // Title
    ws.mergeCells('A1:F1');
    const titleCell = ws.getCell('A1');
    titleCell.value = this.labels.analysisReport;
    titleCell.font = { bold: true, size: 18, color: { argb: 'FF2F5496' } };
    titleCell.alignment = { horizontal: 'center' };
    ws.getRow(1).height = 35;
    
    // Company name
    if (this.options.companyName) {
      ws.mergeCells('A2:F2');
      ws.getCell('A2').value = this.options.companyName;
      ws.getCell('A2').font = { size: 12, color: { argb: 'FF666666' } };
      ws.getCell('A2').alignment = { horizontal: 'center' };
    }
    
    let currentRow = 4;
    
    // Summary section
    const summaryData = [
      [this.labels.totalRows, analysisResult.summary.totalRows],
      [this.labels.totalColumns, analysisResult.summary.totalColumns],
      [this.labels.analysisTime, analysisResult.summary.analysisTime],
      [this.labels.generatedAt, formatDateTime(new Date())],
      [this.labels.generator, 'Excel Intelligence Bot v2.0']
    ];
    
    ws.getCell(`A${currentRow}`).value = '📋 ' + this.labels.summary.toUpperCase();
    ws.getCell(`A${currentRow}`).font = { bold: true, size: 12 };
    currentRow++;
    
    for (const [label, value] of summaryData) {
      ws.getCell(`A${currentRow}`).value = label;
      ws.getCell(`A${currentRow}`).font = { color: { argb: 'FF666666' } };
      ws.getCell(`B${currentRow}`).value = value;
      ws.getCell(`B${currentRow}`).font = { bold: true };
      currentRow++;
    }
    
    currentRow += 2;
    
    // Quality Score Highlight
    const score = analysisResult.qualityScore;
    ws.getCell(`A${currentRow}`).value = '📊 ' + this.labels.qualityScore.toUpperCase();
    ws.getCell(`A${currentRow}`).font = { bold: true, size: 12 };
    currentRow++;
    
    // Big score display
    ws.mergeCells(`A${currentRow}:B${currentRow + 1}`);
    const scoreCell = ws.getCell(`A${currentRow}`);
    scoreCell.value = `${score.overall}%`;
    scoreCell.font = { bold: true, size: 36, color: { argb: this.getScoreColor(score.overall) } };
    scoreCell.alignment = { horizontal: 'center', vertical: 'middle' };
    
    ws.getCell(`C${currentRow}`).value = `Grade: ${score.grade}`;
    ws.getCell(`C${currentRow}`).font = { bold: true, size: 18 };
    ws.getCell(`C${currentRow + 1}`).value = score.gradeLabel;
    ws.getCell(`C${currentRow + 1}`).font = { size: 14, color: { argb: 'FF666666' } };
    
    ws.getRow(currentRow).height = 30;
    ws.getRow(currentRow + 1).height = 25;
    currentRow += 3;
    
    // Issues summary
    if (analysisResult.issues.total > 0) {
      ws.getCell(`A${currentRow}`).value = '⚠️ ' + this.labels.issues.toUpperCase();
      ws.getCell(`A${currentRow}`).font = { bold: true, size: 12 };
      currentRow++;
      
      const bySeverity = analysisResult.issues.bySeverity;
      if (bySeverity.error?.length) {
        ws.getCell(`A${currentRow}`).value = `❌ ${this.labels.error}: ${bySeverity.error.length}`;
        ws.getCell(`A${currentRow}`).font = { color: { argb: 'FFDC3545' } };
        currentRow++;
      }
      if (bySeverity.warning?.length) {
        ws.getCell(`A${currentRow}`).value = `⚠️ ${this.labels.warning}: ${bySeverity.warning.length}`;
        ws.getCell(`A${currentRow}`).font = { color: { argb: 'FFFFC107' } };
        currentRow++;
      }
      if (bySeverity.info?.length) {
        ws.getCell(`A${currentRow}`).value = `ℹ️ ${this.labels.info}: ${bySeverity.info.length}`;
        ws.getCell(`A${currentRow}`).font = { color: { argb: 'FF17A2B8' } };
        currentRow++;
      }
    }
    
    // Column widths
    ws.getColumn('A').width = 25;
    ws.getColumn('B').width = 25;
    ws.getColumn('C').width = 20;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // QUALITY SCORE SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addQualityScoreSheet(workbook, qualityScore) {
    const ws = workbook.addWorksheet(this.labels.qualityScore, {
      properties: { tabColor: { argb: 'FF28A745' } }
    });
    
    // Title
    ws.mergeCells('A1:D1');
    ws.getCell('A1').value = '📊 ' + this.labels.qualityScore;
    ws.getCell('A1').font = { bold: true, size: 16 };
    ws.getRow(1).height = 30;
    
    // Headers
    const headers = [this.labels.type, 'Score', 'Status', 'Visual'];
    ws.addRow(headers);
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2F5496' } };
    headerRow.alignment = { horizontal: 'center' };
    
    // Score data
    const breakdown = qualityScore.breakdown;
    const scoreData = [
      [this.labels.completeness, breakdown.completeness],
      [this.labels.consistency, breakdown.consistency],
      [this.labels.validity, breakdown.validity],
      [this.labels.uniqueness, breakdown.uniqueness]
    ];
    
    for (const [label, score] of scoreData) {
      const row = ws.addRow([
        label,
        `${score}%`,
        this.getScoreStatus(score),
        this.getScoreBar(score)
      ]);
      
      row.getCell(2).font = { bold: true };
      row.getCell(2).alignment = { horizontal: 'center' };
      row.getCell(3).font = { color: { argb: this.getScoreColor(score) } };
      row.getCell(3).alignment = { horizontal: 'center' };
    }
    
    // Overall score
    ws.addRow([]);
    const overallRow = ws.addRow([
      'OVERALL',
      `${qualityScore.overall}%`,
      `Grade: ${qualityScore.grade}`,
      qualityScore.gradeLabel
    ]);
    overallRow.font = { bold: true, size: 12 };
    overallRow.getCell(2).font = { bold: true, size: 14, color: { argb: this.getScoreColor(qualityScore.overall) } };
    
    // Column widths
    ws.getColumn('A').width = 20;
    ws.getColumn('B').width = 12;
    ws.getColumn('C').width = 15;
    ws.getColumn('D').width = 30;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // COLUMN ANALYSIS SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addColumnAnalysisSheet(workbook, columnAnalysis) {
    const ws = workbook.addWorksheet(this.labels.columnAnalysis, {
      properties: { tabColor: { argb: 'FF6F42C1' } }
    });
    
    // Title
    ws.mergeCells('A1:G1');
    ws.getCell('A1').value = '🔍 ' + this.labels.columnAnalysis;
    ws.getCell('A1').font = { bold: true, size: 16 };
    ws.getRow(1).height = 30;
    
    // Headers
    const headers = [
      this.labels.column,
      this.labels.type,
      'Confidence',
      this.labels.fillRate,
      this.labels.uniqueValues,
      'Empty',
      this.labels.samples
    ];
    ws.addRow(headers);
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF6F42C1' } };
    headerRow.alignment = { horizontal: 'center' };
    
    // Data rows
    for (const [colName, analysis] of Object.entries(columnAnalysis)) {
      const row = ws.addRow([
        colName,
        analysis.detectedType,
        `${analysis.confidence}%`,
        `${analysis.fillRate}%`,
        analysis.uniqueCount,
        analysis.emptyCount,
        analysis.sampleValues.slice(0, 3).join(', ')
      ]);
      
      // Color code fill rate
      const fillRateCell = row.getCell(4);
      if (analysis.fillRate < 50) {
        fillRateCell.font = { color: { argb: 'FFDC3545' } };
      } else if (analysis.fillRate < 80) {
        fillRateCell.font = { color: { argb: 'FFFFC107' } };
      } else {
        fillRateCell.font = { color: { argb: 'FF28A745' } };
      }
    }
    
    // Column widths
    ws.getColumn('A').width = 25;
    ws.getColumn('B').width = 15;
    ws.getColumn('C').width = 12;
    ws.getColumn('D').width = 12;
    ws.getColumn('E').width = 15;
    ws.getColumn('F').width = 10;
    ws.getColumn('G').width = 40;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // ISSUES SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addIssuesSheet(workbook, issues) {
    const ws = workbook.addWorksheet(this.labels.issues, {
      properties: { tabColor: { argb: 'FFDC3545' } }
    });
    
    // Title
    ws.mergeCells('A1:F1');
    ws.getCell('A1').value = `⚠️ ${this.labels.issues} (${issues.total})`;
    ws.getCell('A1').font = { bold: true, size: 16 };
    ws.getRow(1).height = 30;
    
    // Headers
    const headers = [
      this.labels.severity,
      this.labels.type,
      this.labels.row,
      this.labels.column,
      this.labels.message,
      this.labels.fix
    ];
    ws.addRow(headers);
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDC3545' } };
    headerRow.alignment = { horizontal: 'center' };
    
    // Issue rows
    for (const issue of issues.details) {
      const row = ws.addRow([
        issue.severity.toUpperCase(),
        issue.type,
        issue.row || '-',
        issue.column || '-',
        issue.message,
        issue.fix || '-'
      ]);
      
      // Color by severity
      const severityCell = row.getCell(1);
      switch (issue.severity) {
        case 'error':
          severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFCCCC' } };
          severityCell.font = { bold: true, color: { argb: 'FFDC3545' } };
          break;
        case 'warning':
          severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF3CD' } };
          severityCell.font = { bold: true, color: { argb: 'FF856404' } };
          break;
        case 'info':
          severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1ECF1' } };
          severityCell.font = { bold: true, color: { argb: 'FF0C5460' } };
          break;
      }
    }
    
    // Column widths
    ws.getColumn('A').width = 12;
    ws.getColumn('B').width = 20;
    ws.getColumn('C').width = 8;
    ws.getColumn('D').width = 20;
    ws.getColumn('E').width = 50;
    ws.getColumn('F').width = 30;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // SUGGESTIONS SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addSuggestionsSheet(workbook, suggestions) {
    const ws = workbook.addWorksheet(this.labels.suggestions, {
      properties: { tabColor: { argb: 'FF17A2B8' } }
    });
    
    // Title
    ws.mergeCells('A1:D1');
    ws.getCell('A1').value = '💡 ' + this.labels.suggestions;
    ws.getCell('A1').font = { bold: true, size: 16 };
    ws.getRow(1).height = 30;
    
    // Headers
    const headers = [
      this.labels.priority,
      this.labels.action,
      this.labels.message,
      this.labels.impact
    ];
    ws.addRow(headers);
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF17A2B8' } };
    headerRow.alignment = { horizontal: 'center' };
    
    // Suggestion rows
    for (const suggestion of suggestions) {
      const row = ws.addRow([
        suggestion.priority.toUpperCase(),
        suggestion.action,
        suggestion.message,
        suggestion.impact
      ]);
      
      // Color by priority
      const priorityCell = row.getCell(1);
      switch (suggestion.priority) {
        case 'high':
          priorityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFCCCC' } };
          priorityCell.font = { bold: true };
          break;
        case 'medium':
          priorityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF3CD' } };
          break;
        case 'low':
          priorityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD4EDDA' } };
          break;
      }
    }
    
    // Column widths
    ws.getColumn('A').width = 12;
    ws.getColumn('B').width = 25;
    ws.getColumn('C').width = 50;
    ws.getColumn('D').width = 35;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // STATISTICS SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addStatisticsSheet(workbook, statistics) {
    const ws = workbook.addWorksheet(this.labels.statistics, {
      properties: { tabColor: { argb: 'FF28A745' } }
    });
    
    // Title
    ws.mergeCells('A1:G1');
    ws.getCell('A1').value = '📈 ' + this.labels.statistics;
    ws.getCell('A1').font = { bold: true, size: 16 };
    ws.getRow(1).height = 30;
    
    // Headers
    const headers = [
      this.labels.column,
      this.labels.count,
      this.labels.sum,
      this.labels.average,
      this.labels.min,
      this.labels.max,
      'Std Dev'
    ];
    ws.addRow(headers);
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF28A745' } };
    headerRow.alignment = { horizontal: 'center' };
    
    // Stats rows
    for (const [colName, stats] of Object.entries(statistics)) {
      const isCurrency = stats.type === 'currency';
      const formatFn = isCurrency ? formatRupiah : formatNumber;
      
      ws.addRow([
        colName,
        stats.count,
        formatFn(stats.sum),
        formatFn(stats.mean, isCurrency ? 0 : 2),
        formatFn(stats.min),
        formatFn(stats.max),
        formatNumber(stats.stdDev, 2)
      ]);
    }
    
    // Column widths
    ws.getColumn('A').width = 25;
    ws.getColumn('B').width = 10;
    ws.getColumn('C').width = 18;
    ws.getColumn('D').width = 18;
    ws.getColumn('E').width = 18;
    ws.getColumn('F').width = 18;
    ws.getColumn('G').width = 12;
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // RAW DATA SHEET
  // ─────────────────────────────────────────────────────────────────────────────

  async addRawDataSheet(workbook, parsedData, sheetName) {
    const sheet = parsedData.sheets[sheetName || parsedData.activeSheet];
    if (!sheet) return;
    
    const ws = workbook.addWorksheet(this.labels.rawData, {
      properties: { tabColor: { argb: 'FF6C757D' } }
    });
    
    // Headers
    ws.addRow(sheet.headers);
    const headerRow = ws.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF6C757D' } };
    
    // Data rows
    for (const row of sheet.rows) {
      ws.addRow(sheet.headers.map(h => row[h] ?? ''));
    }
    
    // Auto filter
    ws.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: sheet.headers.length }
    };
    
    // Freeze header
    ws.views = [{ state: 'frozen', ySplit: 1 }];
    
    // Column widths
    sheet.headers.forEach((h, i) => {
      ws.getColumn(i + 1).width = Math.min(Math.max(h.length + 2, 10), 30);
    });
    
    return ws;
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // DISCORD EMBED REPORT
  // ─────────────────────────────────────────────────────────────────────────────

  /**
   * Generate Discord embed for analysis result
   */
  generateDiscordEmbed(analysisResult) {
    const score = analysisResult.qualityScore;
    const issues = analysisResult.issues;
    const summary = analysisResult.summary;
    
    // Determine embed color based on score
    let color;
    if (score.overall >= 90) color = BOT_CONFIG.COLORS.SUCCESS;
    else if (score.overall >= 70) color = 0x57F287;
    else if (score.overall >= 50) color = BOT_CONFIG.COLORS.WARNING;
    else color = BOT_CONFIG.COLORS.ERROR;
    
    const embed = {
      title: `📊 Hasil Analisis Data`,
      color,
      fields: [
        {
          name: '📋 Ringkasan',
          value: [
            `📁 **Baris:** ${summary.totalRows}`,
            `📊 **Kolom:** ${summary.totalColumns}`,
            `⏱️ **Waktu:** ${summary.analysisTime}`
          ].join('\n'),
          inline: true
        },
        {
          name: '🎯 Skor Kualitas',
          value: [
            `**${score.overall}%** (Grade: ${score.grade})`,
            `${this.getScoreEmoji(score.overall)} ${score.gradeLabel}`
          ].join('\n'),
          inline: true
        },
        {
          name: '📈 Breakdown',
          value: [
            `Kelengkapan: ${score.breakdown.completeness}%`,
            `Konsistensi: ${score.breakdown.consistency}%`,
            `Validitas: ${score.breakdown.validity}%`,
            `Keunikan: ${score.breakdown.uniqueness}%`
          ].join('\n'),
          inline: false
        }
      ],
      timestamp: new Date().toISOString(),
      footer: {
        text: 'Excel Intelligence Bot'
      }
    };
    
    // Add issues summary if any
    if (issues.total > 0) {
      const issuesSummary = [];
      if (issues.bySeverity.error?.length) {
        issuesSummary.push(`❌ ${issues.bySeverity.error.length} Error`);
      }
      if (issues.bySeverity.warning?.length) {
        issuesSummary.push(`⚠️ ${issues.bySeverity.warning.length} Warning`);
      }
      if (issues.bySeverity.info?.length) {
        issuesSummary.push(`ℹ️ ${issues.bySeverity.info.length} Info`);
      }
      
      embed.fields.push({
        name: '⚠️ Masalah Ditemukan',
        value: issuesSummary.join(' | '),
        inline: false
      });
    }
    
    // Add top suggestions
    if (analysisResult.suggestions.length > 0) {
      const topSuggestions = analysisResult.suggestions
        .slice(0, 3)
        .map((s, i) => `${i + 1}. ${s.message}`)
        .join('\n');
      
      embed.fields.push({
        name: '💡 Saran Utama',
        value: topSuggestions,
        inline: false
      });
    }
    
    return embed;
  }

  /**
   * Generate simple text report
   */
  generateTextReport(analysisResult) {
    const lines = [];
    const score = analysisResult.qualityScore;
    const summary = analysisResult.summary;
    
    lines.push('═'.repeat(50));
    lines.push('         LAPORAN ANALISIS DATA');
    lines.push('═'.repeat(50));
    lines.push('');
    lines.push('📋 RINGKASAN');
    lines.push(`   Total Baris    : ${summary.totalRows}`);
    lines.push(`   Total Kolom    : ${summary.totalColumns}`);
    lines.push(`   Waktu Analisis : ${summary.analysisTime}`);
    lines.push('');
    lines.push('📊 SKOR KUALITAS');
    lines.push(`   Overall  : ${score.overall}% (Grade: ${score.grade})`);
    lines.push(`   Status   : ${score.gradeLabel}`);
    lines.push('');
    lines.push('   Breakdown:');
    lines.push(`   - Kelengkapan : ${score.breakdown.completeness}%`);
    lines.push(`   - Konsistensi : ${score.breakdown.consistency}%`);
    lines.push(`   - Validitas   : ${score.breakdown.validity}%`);
    lines.push(`   - Keunikan    : ${score.breakdown.uniqueness}%`);
    lines.push('');
    
    if (analysisResult.issues.total > 0) {
      lines.push('⚠️ MASALAH DITEMUKAN');
      const bySev = analysisResult.issues.bySeverity;
      if (bySev.error?.length) lines.push(`   ❌ Error   : ${bySev.error.length}`);
      if (bySev.warning?.length) lines.push(`   ⚠️ Warning : ${bySev.warning.length}`);
      if (bySev.info?.length) lines.push(`   ℹ️ Info    : ${bySev.info.length}`);
      lines.push('');
    }
    
    if (analysisResult.suggestions.length > 0) {
      lines.push('💡 SARAN PERBAIKAN');
      analysisResult.suggestions.slice(0, 5).forEach((s, i) => {
        lines.push(`   ${i + 1}. [${s.priority.toUpperCase()}] ${s.message}`);
      });
      lines.push('');
    }
    
    lines.push('═'.repeat(50));
    lines.push(`Generated: ${new Date().toLocaleString('id-ID')}`);
    lines.push('Excel Intelligence Bot v2.0');
    lines.push('═'.repeat(50));
    
    return lines.join('\n');
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // HELPER METHODS
  // ─────────────────────────────────────────────────────────────────────────────

  getScoreColor(score) {
    if (score >= 90) return 'FF28A745'; // Green
    if (score >= 70) return 'FF17A2B8'; // Blue
    if (score >= 50) return 'FFFFC107'; // Yellow
    return 'FFDC3545'; // Red
  }

  getScoreStatus(score) {
    if (score >= 90) return 'Excellent';
    if (score >= 70) return 'Good';
    if (score >= 50) return 'Fair';
    if (score >= 25) return 'Poor';
    return 'Very Poor';
  }

  getScoreEmoji(score) {
    if (score >= 90) return '🌟';
    if (score >= 70) return '✅';
    if (score >= 50) return '⚠️';
    return '❌';
  }

  getScoreBar(score) {
    const filled = Math.round(score / 10);
    const empty = 10 - filled;
    return '█'.repeat(filled) + '░'.repeat(empty) + ` ${score}%`;
  }
}

// Create singleton
export const reportGenerator = new ReportGenerator();

export default {
  ReportGenerator,
  reportGenerator
};
